# Generated by Django 6.0.5 on 2026-06-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('education', models.TextField()),
                ('skills', models.TextField()),
                ('projects', models.TextField()),
                ('template', models.CharField(choices=[('modern', 'Modern'), ('professional', 'Professional'), ('developer', 'Developer')], max_length=20)),
            ],
        ),
    ]
