# Generated by Django 6.0.5 on 2026-06-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.AddField(
            model_name='resume',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='full_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='hobbies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('student', 'Student'), ('professional', 'Professional'), ('modern', 'Modern'), ('creative', 'Creative'), ('developer', 'Developer'), ('executive', 'Executive')], default='student', max_length=20),
        ),
    ]
